language: node_js

script: yarn test && yarn lint

before_deploy:
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
    
      git config --local user.name "David Correa"
      git config --local user.email "davidjonatan.c@gmail.com"
      export TRAVIS_TAG=${TRAVIS_TAG:-'Release'-$(date +'%Y-%m-%d-%H%M%S')}
      git tag $TRAVIS_TAG

      yarn run build
    fi

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    target-branch: gh-pages
    local-dir: build
    on:
      branch: master

  - provider: releases
    name: "Revolución Industrial - 3Pines"
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      branch: master