language: node_js

node_js:
  - "11"

services: 
  - mongodb

before_script: 
  - cd back-end && yarn install && cd ..
  - cd front-end && yarn install && cd ..

script:
  - cd back-end && yarn test-ci && cd ..
  - cd front-end && yarn test && yarn lint && cd ..

before_deploy:
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
    
      git config --local user.name "David Correa"
      git config --local user.email "davidjonatan.c@gmail.com"
      export TRAVIS_TAG=${TRAVIS_TAG:-'Release'-$(date +'%Y-%m-%d-%H%M%S')}
      git tag $TRAVIS_TAG

      cd front-end/ && yarn run build
      cd ..
    fi

deploy:
  - provider: script
    script: bash ./scripts/build-images.sh $DOCKER_USERNAME $DOCKER_PASSWORD
    on:
      branch: master

  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    target-branch: gh-pages
    local-dir: front-end/build
    on:
      branch: master

  - provider: releases
    name: "Revolución Industrial - 3Pines"
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      branch: master    